### ISSUE TITLE
Send logs via UPD does not track that server is not alive

### ISSUE THREAD

**Issue by diomaz** [luigiberrettini/NLog.Targets.Syslog#278]
In our infrastructure we have several docker containers listening on syslog messages. They listening on upd-port on different IP-addresses. Sometimes on of them can be down but another containers continue to work.
NLog.Targets.Syslog alows specify UDP as a trasport. But...
When you create instance of SyslogTarget specified Server resolves to IP-address and it keeps during application is alive.
Also NLog.Targets.Syslog supports reconnects when something is wrong while sending request but...
The nature of UPD is that it send request and doesn't wait response. So, when you send logs to died server, you can't know: is server alive or not, and reconnect will never happen, so reconnect-feature is useless.
If you added reconnect-feature it will be great to have it worked even for UDP

**Comment by luigiberrettini** [comment]
The `SendMessageAsync` method of the `MessageTransmitter` class [retries transmissions](https://github.com/luigiberrettini/NLog.Targets.Syslog/blob/v6.0.2/src/NLog.Targets.Syslog/MessageSend/MessageTransmitter.cs#L60-L72) when an exception is triggered before the `ContinueWith` and this is mostly useful when an error occurs while sending TCP/UDP messages with the `SendAsync` method.

With regard to UDP this [means](https://github.com/luigiberrettini/NLog.Targets.Syslog/blob/v6.0.2/src/NLog.Targets.Syslog/MessageSend/Udp.cs#L33) that `UdpClient.SendAsync` triggered an exception and looking at the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.udpclient.sendasync?view=netstandard-2.0) it is easy to see that `SocketException` is the best bet.

Unfortunately, due to the connectionless nature of UDP most network problems won't be detected and even if using TCP it is not possible to detect all of them.

I understand that this might be frustrating, but I was not able to find a way to handle this kind of issues.
Should you have a solution, please do not hesitate to submit a PR.
