### ISSUE TITLE
Is the name of the Target always {my name}_wrapped?

### ISSUE THREAD

**Issue by dstahl-axion** [luigiberrettini/NLog.Targets.Syslog#283]
**Ask the question**
Hi!

I'm trying to programmatically modify my list of targets & rules after the application has started up. I've found that when I look at the list of Targets and find the SyslogTargets the name is always whatever I define plus the suffix `_wrapped`. 

For example, if my config looks like this:

```xml
  <target xsi:type="sl:Syslog" name="syslogger2">
            <sl:layout xsi:type="SimpleLayout">
                <text>${syslog_layout}</text>
            </sl:layout>
```

In code, if I do:

```c#
Syslogger logger = ...; // code to fetch the logger

logger.Name == "syslogger2_wrapped" // is TRUE!
```

Is that always the case?

These are my versions:

**Additional context**
 - NLog version: 4.7.10
 - NLog.Targets.Syslog version [e.g. 6.0.2]

**Comment by luigiberrettini** [comment]
Hi @dstahl-axion the target does not do anything special regarding loggers.

Debugging and looking at NLog code, I saw that the target name is as per configuration whereas the logger name depends on whether you called `LogManager.GetCurrentClassLogger()` or `LogManager.GetLogger(name)` to instantiate the Logger.

**Comment by dstahl-axion** [comment]
@luigiberrettini thanks for replying. This is interesting!

To make sure we are talking about the same thing, the "code to fetch the logger" is something like this:

```c#
// Find the first syslog target. 
// Per my config file, the name of the target is "syslogger2"
var syslogTarget =   LogManager.Configuration.AllTargets.OfType<SyslogTarget>().First();

Console.WriteLine($"Target name is: {syslogTarget.Name}"); // prints "syslogger2_wrapped"
```

I *just* realized that my config file has this:

```xml
<targets async="true">
```

Perhaps the _wrapped is related to the application of an async target?

**Comment by luigiberrettini** [comment]
The word logger made me think you were looking at the name of a `Logger` object instead of a `Target` one.

As you suggested I think that using [wrapper targets](https://nlog-project.org/config/?tab=targets&search=wrapper) can cause the wrapped target name to have a `_wrapper` suffix.

Please note that, as stated in the [configuration doc](https://github.com/luigiberrettini/NLog.Targets.Syslog/blob/master/docs/configuration.md), the NLog Syslog target takes advantage of the [.NET Task Parallel Library](https://msdn.microsoft.com/en-us/library/dd460717.aspx) to work in an asynchronous and concurrent way, therefore the NLog **AsyncWrapper** should not be used.
